[tool.poetry]
name = "my-courses"
version = "0.1.0"
description = ""
authors = ["yanice <yanice.moreau@decathlon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
